global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг Security Demo приложения
  - job_name: 'security-demo'
    static_configs:
      - targets: ['web:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    
  # Можно добавить дополнительные targets
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] 