services:
  web:
    build: .
    container_name: simple-security-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=1
    restart: unless-stopped

  zap:
    image: owasp/zap2docker-stable
    container_name: security-zap
    command: zap-baseline.py -t http://web:5000 -J zap-report.json
    volumes:
      - ./reports:/zap/wrk:rw
    depends_on:
      - web
    profiles:
      - security-scan

volumes:
  data: 